1. detect error during workspace/run script 2. build-in vscode-server in docker image 3. auto remove 127.0.0.1 record in known_hosts list before start SSH connection

diff --git a/workspace/run b/workspace/run
--- a/workspace/run
+++ b/workspace/run
@@ -3,6 +3,8 @@
 IMAGE_NAME="wfas-workspace"
 CONTAINER_NAME="wfas-workspace"
 
+set -e
+
 cd $(dirname "$0")
 
 usage_message(){
@@ -23,15 +25,18 @@ EOF
 start_environment() {
     if [[ "$(docker images -q $IMAGE_NAME)" == "" ]]; then
         cp ../Server/requirements.txt ./server_requirements.txt > /dev/null 2>&1 || touch server_requirements.txt
-        docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g)  -t $IMAGE_NAME .
+        docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g)  -t $IMAGE_NAME . \
+            || { echo "error due to docker build image" && exit 1; }
         rm server_requirements.txt
     fi
 
     if [[ "$(docker ps | grep $CONTAINER_NAME)" == "" ]]; then
-        docker run -v /"$PWD"/../:/workspace/ -p 22:22 -p 5000:5000 --name $CONTAINER_NAME -d $IMAGE_NAME
+        docker run -v /"$PWD"/../:/workspace/ -p 22:22 -p 5000:5000 --name $CONTAINER_NAME -d $IMAGE_NAME \
+            || { echo "error due to docker build image" && exit 1; }
     fi
 
     if [ $OSTYPE == "msys" ]; then
+        sed -i '/127.0.0.1/d' ~/.ssh/known_hosts
         CONTAINER_IP="$(docker inspect --format="{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" $CONTAINER_NAME)"
     else
         CONTAINER_IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_NAME)"
@@ -55,11 +60,7 @@ remove_docker_image() {
 
 export DOCKER_SCAN_SUGGEST=false
 
-docker version > /dev/null 2>&1
-if [[ $? != 0 ]]; then
-    echo "error: please install and start Docker Engine first!!!"
-    exit 1
-fi
+[[ $(docker ps > /dev/null 2>&1; echo $?) != 0 ]] && echo "error: please install and start Docker Engine first!!!" && exit 1
 
 case $1 in 
     --start )
